<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

define('DB_HOST',':/var/run/mysql/mysql.sock');
define('DB_USER','');
define('DB_PASS','');
define('DB_DATABASE','');
define('SMARTY_DIR','/www-kyberia/inc/smarty/');
define('SYSTEM_ROOT','/www-kyberia/');
define('TEMPLATE_DIR','/www-kyberia/data/templates/');
define('OWN_TEMPLATE_DIR',TEMPLATE_DIR.'own_templates/');
define('TMP','/www-root/www-kyberia/tmp');
define('PEAR_DIR','/usr/local/lib/php/');
define('DEFAULT_LISTING_AMOUNT','32');
define('DEFAULT_LISTING_ORDER','desc');
define('DEFAULT_TEMPLATE_ID','4');
define('FILE_DIR','/storage/data/file_nodes/');
define('FILE_URL','http://h-k.sk/files/');
define('UTILZ_DIR','/www-root/www-kyberia/utilz/');
define('VECTOR_CHARS',8);
define('NODE_IMAGE_WIDTH',123);
define('URI','https://hysteria.sk/id/'
define('URI','http://www.kyberia.sk/id/');
define('TEMPLATE_SET','kyberia');




?>
