<?php
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

$error_messages['K_EGOTRIP']="kcka si davas, brusko si mastis?";
$error_messages['K_GIVEN']="datanode uz si k udelil.uz to nehul";
$error_messages['K_SPENT']="nemas k. call dara rollins if you're stupid or john lilly if you're trendy";
$error_messages['NEW_PASSWORD_MISMATCH']="password don't match, try again";
$error_messages['INCORRECT_TEMPLATE_ID']="incorrect template_id";
$error_messages['INCORRECT_VECTOR']="incorrect vector";
$error_messages['WRITE_PERMISSION_ERROR']="nemas dostatocne prava na zapis do dotycnej nody";
$error_messages['READ_PERMISSION_ERROR']="nemas dostatocne prava na citanie obsahu tejto nody. PROSTE NEMAS DOSTATOCNE PRAVA NA CITANIE OBSAHU TEJTO NODY. JE TI TO JASNE?";
$error_messages['EVENT_PERMISSION_ERROR']="nemas dostatocne prava na vykonanie tohto skutku. jses proklet do sesteho kolena";
$error_messages['ADD_NO_CONTENT']='Noda bez obsahu sa pridat neda. Prosto neda. A basta.';
$error_messages['USER_NOT_FOUND']='user s dotycnym menom neexistuje. alebo existuje iba v tvojich predstavach';
$error_messages['EVENT_NOT_EXISTENT']='toto nieje svet v ktorom by sa dali vykonavat cinnosti ktore neexistuju';
$error_messages['EVENT_NOT_PERMITTED']='su veci na ktore prosto nemas pravo';
?>