<!-- BBSTART: ad2.billboard.cz kod 1.1 - SERVER: Server(7587), SEKCE: main page(1), POZICE: (1), TYPBANNERU: Skyscraper(9), OKRAJ: ne, POPIS: ne. -->
<script language='JavaScript' type='text/javascript'>
<!--
var bbs=screen,bbn=navigator,bbh;bbh='&ubl='+bbn.browserLanguage+'&ucc='+bbn.cpuClass+'&ucd='+bbs.colorDepth+'&uce='+bbn.cookieEnabled+'&udx='+bbs.deviceXDPI+'&udy='+bbs.deviceYDPI+'&usl='+bbn.systemLanguage+'&uje='+bbn.javaEnabled()+'&uah='+bbs.availHeight+'&uaw='+bbs.availWidth+'&ubd='+bbs.bufferDepth+'&uhe='+bbs.height+'&ulx='+bbs.logicalXDPI+'&uly='+bbs.logicalYDPI+'&use='+bbs.fontSmoothingEnabled+'&uto='+(newDate()).getTimezoneOffset()+'&uui='+bbs.updateInterval+'&uul='+bbn.userLanguage+'&uwi='+bbs.width;
var bb9_bgcolor='C0C0C0';
var bb9_text='000000';
var bb9_link='0000FF';
if(document.bgColor) { bb9_bgcolor=document.bgColor.substr(1); }
if(document.fgColor) { bb9_text=document.fgColor.substr(1); }
if(document.linkColor) { bb9_link=document.linkColor.substr(1); }
document.write("<IFRAME WIDTH=120 HEIGHT=600 MARGINWIDTH=0 MARGINHEIGHT=0 FRAMEBORDER=0 HSPACE=0 VSPACE=0 SCROLLING=no BORDERCOLOR='#000000' SRC='http://ad2.billboard.cz/please/showit/7587/1/1/9/?typkodu=html&topmargin=0&leftmargin=0"+bbh+"&href="+escape(location.href)+"&popis=ne&okraj=ne&bgcolor="+bb9_bgcolor+"&text="+bb9_text+"&link="+bb9_link+"&bust="+Math.random()+"&target=_top'>");
document.write("<scr"+"ipt language='JavaScript' type='text/javascript'>");
document.write("document.write(\"<scr\"+\"ipt language='JavaScript' type='text/javascript' src='http://ad2.billboard.cz/please/showit/7587/1/1/9/?typkodu=js\"+bbh+\"&href=\"+escape(location.href)+\"&popis=ne&okraj=ne&bust=\"+Math.floor(10000000*Math.random())+\"&target=_top'><\/scr\"+\"ipt>\");");
document.write("<\/scr"+"ipt>");
document.write("<\/IFRAME>");
/**///-->
</script>
<noscript>
<table border="0" cellpadding="0" cellspacing="0"><tr><td>
<a href="http://ad2.billboard.cz/please/redir.bb/7587/1/1/9/" target="_top">
<img src="http://ad2.billboard.cz/please/showit/7587/1/1/9/?typkodu=img" border="0" width="120" height="600" alt='Kliknete prosim!'></a>
</td></tr></table>
</noscript>
<!-- BBEND: ad2.billboard.cz kod 1.1 -->
