<table width=100% class=box><tr><td align=center>
<?
global $id;
$value=$kyberia->putGallery($_GET['node_id']);
if (!$value) {
?>

foto z <a href=http://kyberia.sk/gallery>galerie</a>
<br><a href=http://kyberia.sk/gallery/view_photo.php?set_albumName=Klute-Smirnoff-in-da-bush&id=aaz>
<br><img src=http://kyberia.sk/images/albums/Klute-Smirnoff-in-da-bush/aaz.thumb.jpg border=0 >
</a>
<br>
<? } ?>
</td></tr></table>
