harddisk na mojom homeserveri zdochol..takze irc chvilu nebude
<!--
<b>toto je testovaci modul, pomocou bota substance sa vsetko z kanalov <br>
<a href='?action=irc&channel=kyberia'>#kyberia</a>,
<a href='?action=irc&channel=ragtime'>#ragtime</a>,
<a href='?action=irc&channel=bajkonur'>#bajkonur</a><br><br>
-->
<?php
/*
$sqlcmd="select * from irc_messages where channel like '$channel' order by message_id desc limit 23";
//echo $sqlcmd;
$result=mysql_query($sqlcmd);
while ($riadok=mysql_fetch_array($result)) {
	echo "<table class='bigitem'><tr><td class='icon'>";
	echo "<img width='50' alt='",$riadok['nick'],"' src='/images/users/",strtolower($riadok['nick']),".gif'>";	
	echo "</td><td class='item'>";
	echo "<table class='item'>";
	echo "<td class='header'>",$riadok['nick']," [<font color='white'>",$riadok['host'],"</font>]";

	Showz::showDate($riadok['time']);
	echo "</td>";
	echo "</tr>";
	echo "<tr class='content'><td class='content'>",Stripslashes($riadok['message_text']),"</td></tr>";
	echo "</table>";
	echo "</td></tr></table>";

}


*/
?>
