<div id="loginbox">
<table  class=menubox width=107>
<form action="<?=SCRIPT?>" method=post>
<input type='hidden' name='action' value='login'>
<tr><Td align=center>login:<input class='textinput' type=text name=login></td></tr>
<tr><Td align=center>heslo:<input type=password class='textinput' name='password'></td></tr>
<tr><Td align=center><input type=submit name=event value="login" class='bigtextinput'>
<tr><Td align=center><a href='<?=SCRIPT?>?action=register'>zaregistruj sa</a>
</form>
</table>

</div>
