<br>
<table width=100% class=box><tr>
<Td><center><a href=http://kyberia.sk/journaux.php?action=add><img src=http://zion.sk/obrazky/kyberia/anchor.gif border=0></td><td><a href=http://kyberia.sk/journaux.php?action=add>Vytvorenie profilu</a></center></td>
</tr><tr><td><center><a href=http://kyberia.sk/journaux.php?action=dennikadd><img src=http://zion.sk/obrazky/kyberia/anchor.gif border=0></td><td><a href=http://kyberia.sk/journaux.php?action=dennikadd>Napisat novy zapis</a></center>
</table>
<br>