<!-- AdSpace site=kyberia.sk size=na cid=mmm width=468 height=240 --> 
<div id='ad'> 
<SCRIPT LANGUAGE="JavaScript"> 
<!-- 
bust=Math.floor(1000000*Math.random()); 
document.write('<IFRAME WIDTH=468 HEIGHT=60 ALLOWTRANSPARENCY=1 MARGINWIDTH=0 MARGINHEIGHT=0 FRAMEBORDER=0 HSPACE=0 VSPACE=0 SCROLLING=no BORDERCOLOR="#000000" SRC="http://asn.premium.cz/html.ng/Params.styles=transparent&site=kyberia.sk&size=na&cid=mmm&bust='+bust+'">\n'); 
document.write('<SCR' + 'IPT LANGUAGE="JavaScript1.1" SRC="http://asn.premium.cz/js.ng/Params.richmedia=yes&site=kyberia.sk&size=na&cid=mmm&bust='+bust+'">\n'); 
document.write('</SCR' + 'IPT>'); 
document.write('</IFRAME>'); 
//--> 
</SCRIPT> 
<NOSCRIPT> 
<A HREF="http://asn.premium.cz/click.ng/Params.richmedia=yes&site=kyberia.sk&size=na&cid=mmm" TARGET="_top"> 
<IMG SRC="http://asn.premium.cz/image.ng/Params.richmedia=yes&site=kyberia.sk&size=na&cid=mmm" WIDTH=468 HEIGHT=60 border=0></A> 
</NOSCRIPT> 
</div> 
<!-- /AdSpace -->