<table class='box'><tr><td><font color='red'><center><b>Poziadal si o vstup do autonomnej zony!</b></center></font><br>Kyberia je  komunita ludi ktory mozu byt roztruseny po celom svete a predsa vedia ze su sucastou toho isteho
naroda. Nie naroda Cechov alebo Slovakov, ale naroda bytosti ktore chcu byt stastne a slobodne.
Preto jedine pravidlo ktore na kyberii plati je <b>rob si co chces ale pamataj na to ze aj
ostatny si budu robiet co chcu</b>. Ak chces nadavat, vyvolavat konflikty a posielat ludi dopice,
prosim, mas na to pravo, ale potom sa necuduj ze posleme dopice aj my teba. Nechceme giganticku
navstevnost ani byt co najvacsi. Chceme absolutne slobodnu vymenu informacii - nic nieje tabu v svete zlozenom
zo zakladnych jednotiek 0 a 1. Chceme vzajomnou interakciou posuvat jeden druheho dalej - az k
poznaniu ze tam niekde vnutri sme vsetci iba inymi projekciami toho isteho filmu. </td></tr></table>