<center><b>hladaj</b>
<form method='post'>
<select style='width: 80px;' name='type'>
<option value='forum'>forum</option>
<option value='user'>cloveka</option>
<option value='journaux'>dennik</option>
<option value='article'>clanok</option>
</select><br>
<input type='text' style='input' name='query'>
<input type='hidden' name='action' value='searchforum'>
<input type='submit' value='hla.daj'>
</form></center>